config:
  backup: true
  banner: false
  create: true
  dotpath: conf
dotfiles:
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_fdignore:
    src: fdignore
    dst: ~/.fdignore
  f_rgignore:
    src: rgignore
    dst: ~/.rgignore
  f_ripgreprc:
    src: ripgreprc
    dst: ~/.ripgreprc
  d_gammastep:
    src: config/gammastep
    dst: ~/.config/gammastep
  f_ini:
    src: config/mc/ini
    dst: ~/.config/mc/ini
  d_doom:
    src: config/doom
    dst: ~/.config/doom
    cmpignore:
    - '*/custom.el'
    - '*/env.el'
    upignore:
    - '*/custom.el'
    - '*/env.el'
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
    chmod: '600'
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
  f_user-dirs.locale:
    src: config/user-dirs.locale
    dst: ~/.config/user-dirs.locale
  f_ec.desktop:
    src: local/share/applications/ec.desktop
    dst: ~/.local/share/applications/ec.desktop
  f_00-keyboard.conf:
    src: etc/X11/xorg.conf.d/00-keyboard.conf
    dst: /etc/X11/xorg.conf.d/00-keyboard.conf
  f_vconsole.conf:
    src: etc/vconsole.conf
    dst: /etc/vconsole.conf
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  f_config.kdl:
    src: config/zellij/config.kdl
    dst: ~/.config/zellij/config.kdl
  f_config.sh:
    src: config/dmenu-translate/config.sh
    dst: ~/.config/dmenu-translate/config.sh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config.org:
    src: config/emacs/config.org
    dst: ~/.config/emacs/config.org
  f_early-init.el:
    src: config/emacs/early-init.el
    dst: ~/.config/emacs/early-init.el
  f_init.el:
    src: config/emacs/init.el
    dst: ~/.config/emacs/init.el
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_fish_plugins:
    src: config/fish/fish_plugins
    dst: ~/.config/fish/fish_plugins
  f_ec:
    src: bin/ec
    dst: ~/.bin/ec
    chmod: '755'
  f_gammastep.sh:
    src: bin/gammastep.sh
    dst: ~/.bin/gammastep.sh
    chmod: '755'
  f_keyboard.sh:
    src: bin/keyboard.sh
    dst: ~/.bin/keyboard.sh
    chmod: '755'
  f_thinkpad-leds.sh:
    src: bin/thinkpad-leds.sh
    dst: ~/.bin/thinkpad-leds.sh
    chmod: '755'
  f_unclutter.sh:
    src: bin/unclutter.sh
    dst: ~/.bin/unclutter.sh
    chmod: '755'
  f_buffer-move.el:
    src: config/emacs/scripts/buffer-move.el
    dst: ~/.config/emacs/scripts/buffer-move.el
  f_elpaca-setup.el:
    src: config/emacs/scripts/elpaca-setup.el
    dst: ~/.config/emacs/scripts/elpaca-setup.el
  f_themes.org:
    src: config/emacs/scripts/themes.org
    dst: ~/.config/emacs/scripts/themes.org
  f_postswitch:
    src: config/autorandr/postswitch
    dst: ~/.config/autorandr/postswitch
    chmod: '755'
  f_lock-screen.sh:
    src: bin/lock-screen.sh
    dst: ~/.bin/lock-screen.sh
    chmod: '755'
  f_profile:
    src: profile
    dst: ~/.profile
  f_ec-editor:
    src: bin/ec-editor
    dst: ~/.bin/ec-editor
    chmod: '755'
  f_ec-visual:
    src: bin/ec-visual
    dst: ~/.bin/ec-visual
    chmod: '755'
  f_alacritty.toml:
    src: config/alacritty/alacritty.toml
    dst: ~/.config/alacritty/alacritty.toml
  f_default.kdl:
    src: config/zellij/layouts/default.kdl
    dst: ~/.config/zellij/layouts/default.kdl
  f_config:
    src: config/mako/config
    dst: ~/.config/mako/config
  f_brave-flags.conf:
    src: config/brave-flags.conf
    dst: ~/.config/brave-flags.conf
  f_chrome-flags.conf:
    src: config/chrome-flags.conf
    dst: ~/.config/chrome-flags.conf
  f_chromium-flags.conf:
    src: config/chromium-flags.conf
    dst: ~/.config/chromium-flags.conf
  f_tlp.conf:
    src: etc/tlp.conf
    dst: /etc/tlp.conf
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_index.theme:
    src: local/share/icons/default/index.theme
    dst: ~/.local/share/icons/default/index.theme
  f_70-backlight.rules:
    src: etc/udev/rules.d/70-backlight.rules
    dst: /etc/udev/rules.d/70-backlight.rules
  f_yandex-music.conf:
    src: config/yandex-music.conf
    dst: ~/.config/yandex-music.conf
  f_ghostty_config:
    src: config/ghostty/config
    dst: ~/.config/ghostty/config
  f_brightness.sh:
    src: bin/brightness.sh
    dst: ~/.bin/brightness.sh
    chmod: '755'
  f_51-mitigate-annoying-profile-switch.conf:
    src: config/wireplumber/wireplumber.conf.d/51-mitigate-annoying-profile-switch.conf
    dst: 
      ~/.config/wireplumber/wireplumber.conf.d/51-mitigate-annoying-profile-switch.conf
  f_split-flac.sh:
    src: bin/split-flac.sh
    dst: ~/.bin/split-flac.sh
    chmod: '755'
  f_multicd.fish:
    src: config/fish/functions/multicd.fish
    dst: ~/.config/fish/functions/multicd.fish
  f_99-power-profile.rules:
    src: etc/udev/rules.d/99-power-profile.rules
    dst: /etc/udev/rules.d/99-power-profile.rules
  f_aider.conf.yml:
    src: aider.conf.yml
    dst: ~/.aider.conf.yml
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  f_set-android-layout.sh:
    src: bin/set-android-layout.sh
    dst: ~/.bin/set-android-layout.sh
    chmod: '755'
  f_razer.conf:
    src: config/openrazer/razer.conf
    dst: ~/.config/openrazer/razer.conf
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_monitors.sh:
    src: bin/monitors.sh
    dst: ~/.bin/monitors.sh
    chmod: '755'
  f_emacs-pager.sh:
    src: bin/emacs-pager.sh
    dst: ~/.bin/emacs-pager.sh
  f_y.fish:
    src: config/fish/functions/y.fish
    dst: ~/.config/fish/functions/y.fish
  f_theme.conf:
    src: config/kitty/theme.conf
    dst: ~/.config/kitty/theme.conf
  f_post-hibernate-user.service:
    src: etc/systemd/system/post-hibernate-user.service
    dst: /etc/systemd/system/post-hibernate-user.service
profiles:
  hyper-city:
    dotfiles:
    - f_editorconfig
    - f_fdignore
    - f_rgignore
    - f_ripgreprc
    - d_gammastep
    - f_ini
    - f_mimeapps.list
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_ec.desktop
    - f_config.kdl
    - f_config.sh
    - f_gitconfig
    - f_config.org
    - f_early-init.el
    - f_init.el
    - f_config.fish
    - f_fish_plugins
    - f_ec
    - f_keyboard.sh
    - f_thinkpad-leds.sh
    - f_unclutter.sh
    - f_buffer-move.el
    - f_elpaca-setup.el
    - f_themes.org
    - f_lock-screen.sh
    - f_profile
    - f_ec-editor
    - f_ec-visual
    - f_alacritty.toml
    - f_default.kdl
    - f_config
    - f_brave-flags.conf
    - f_chrome-flags.conf
    - f_chromium-flags.conf
    - d_waybar
    - f_xresources
    - f_index.theme
    - f_yandex-music.conf
    - f_ghostty_config
    - f_brightness.sh
    - f_51-mitigate-annoying-profile-switch.conf
    - f_split-flac.sh
    - f_multicd.fish
    - f_aider.conf.yml
    - d_dunst
    - f_set-android-layout.sh
    - f_razer.conf
    - f_kitty.conf
    - f_emacs-pager.sh
    - f_y.fish
    - f_theme.conf
  ismd-work:
    dotfiles:
    - f_editorconfig
    - f_fdignore
    - f_rgignore
    - f_ripgreprc
    - d_gammastep
    - f_ini
    - d_doom
    - f_mimeapps.list
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_ec.desktop
    - f_vconsole.conf
    - f_tmux.conf
    - f_config.kdl
    - f_config.sh
    - f_gitconfig
    - f_config.org
    - f_early-init.el
    - f_init.el
    - f_config.fish
    - f_fish_plugins
    - f_ec
    - f_gammastep.sh
    - f_keyboard.sh
    - f_thinkpad-leds.sh
    - f_unclutter.sh
    - f_buffer-move.el
    - f_elpaca-setup.el
    - f_themes.org
    - f_lock-screen.sh
    - f_profile
    - f_ec-editor
    - f_ec-visual
    - f_alacritty.toml
    - f_default.kdl
    - f_config
    - f_brave-flags.conf
    - f_chrome-flags.conf
    - f_chromium-flags.conf
    - d_waybar
    - f_xresources
    - f_index.theme
    - f_70-backlight.rules
    - f_yandex-music.conf
    - f_ghostty_config
    - f_brightness.sh
    - f_51-mitigate-annoying-profile-switch.conf
    - f_split-flac.sh
    - f_multicd.fish
    - f_99-power-profile.rules
    - f_aider.conf.yml
    - d_dunst
    - f_set-android-layout.sh
    - f_razer.conf
    - f_kitty.conf
    - f_monitors.sh
    - f_emacs-pager.sh
    - f_y.fish
    - f_theme.conf
    - f_post-hibernate-user.service
  ismd-black:
    dotfiles:
    - f_editorconfig
    - f_fdignore
    - f_rgignore
    - f_ripgreprc
    - d_gammastep
    - f_ini
    - d_doom
    - f_mimeapps.list
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_ec.desktop
    - f_vconsole.conf
    - f_tmux.conf
    - f_config.kdl
    - f_config.sh
    - f_gitconfig
    - f_config.org
    - f_early-init.el
    - f_init.el
    - f_config.fish
    - f_fish_plugins
    - f_ec
    - f_gammastep.sh
    - f_keyboard.sh
    - f_thinkpad-leds.sh
    - f_unclutter.sh
    - f_buffer-move.el
    - f_elpaca-setup.el
    - f_themes.org
    - f_lock-screen.sh
    - f_profile
    - f_ec-editor
    - f_ec-visual
    - f_alacritty.toml
    - f_default.kdl
    - f_config
    - f_brave-flags.conf
    - f_chrome-flags.conf
    - f_chromium-flags.conf
    - d_waybar
    - f_xresources
    - f_index.theme
    - f_70-backlight.rules
    - f_yandex-music.conf
    - f_ghostty_config
    - f_brightness.sh
    - f_51-mitigate-annoying-profile-switch.conf
    - f_split-flac.sh
    - f_multicd.fish
    - f_99-power-profile.rules
    - f_aider.conf.yml
    - d_dunst
    - f_set-android-layout.sh
    - f_razer.conf
    - f_kitty.conf
    - f_monitors.sh
    - f_emacs-pager.sh
    - f_y.fish
    - f_theme.conf
    - f_post-hibernate-user.service
