config:
  backup: true
  banner: false
  create: true
  dotpath: conf
dotfiles:
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_fdignore:
    src: fdignore
    dst: ~/.fdignore
  f_rgignore:
    src: rgignore
    dst: ~/.rgignore
  f_ripgreprc:
    src: ripgreprc
    dst: ~/.ripgreprc
  d_gammastep:
    src: config/gammastep
    dst: ~/.config/gammastep
  f_ini:
    src: config/mc/ini
    dst: ~/.config/mc/ini
  d_doom:
    src: config/doom
    dst: ~/.config/doom
    cmpignore:
    - '*/custom.el'
    - '*/env.el'
    upignore:
    - '*/custom.el'
    - '*/env.el'
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
  f_user-dirs.locale:
    src: config/user-dirs.locale
    dst: ~/.config/user-dirs.locale
  f_ec.desktop:
    src: local/share/applications/ec.desktop
    dst: ~/.local/share/applications/ec.desktop
  f_00-keyboard.conf:
    src: etc/X11/xorg.conf.d/00-keyboard.conf
    dst: /etc/X11/xorg.conf.d/00-keyboard.conf
  f_vconsole.conf:
    src: etc/vconsole.conf
    dst: /etc/vconsole.conf
  f_theme.bash:
    src: config/i3/themes/landscape/theme.bash
    dst: ~/.config/i3/themes/landscape/theme.bash
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  f_config.kdl:
    src: config/zellij/config.kdl
    dst: ~/.config/zellij/config.kdl
  d_scripts:
    src: config/i3/scripts
    dst: ~/.config/i3/scripts
  f_config.sh:
    src: config/dmenu-translate/config.sh
    dst: ~/.config/dmenu-translate/config.sh
  d_config.d:
    src: config/i3/config.d
    dst: ~/.config/i3/config.d
  f_config.ini:
    src: config/i3/themes/landscape/polybar/config.ini
    dst: ~/.config/i3/themes/landscape/polybar/config.ini
  f_modules.ini:
    src: config/i3/themes/landscape/polybar/modules.ini
    dst: ~/.config/i3/themes/landscape/polybar/modules.ini
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config.org:
    src: config/emacs/config.org
    dst: ~/.config/emacs/config.org
  f_early-init.el:
    src: config/emacs/early-init.el
    dst: ~/.config/emacs/early-init.el
  f_init.el:
    src: config/emacs/init.el
    dst: ~/.config/emacs/init.el
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_fish_plugins:
    src: config/fish/fish_plugins
    dst: ~/.config/fish/fish_plugins
  f_ec:
    src: bin/ec
    dst: ~/.bin/ec
    chmod: '755'
  f_gammastep.sh:
    src: bin/gammastep.sh
    dst: ~/.bin/gammastep.sh
    chmod: '755'
  f_keyboard.sh:
    src: bin/keyboard.sh
    dst: ~/.bin/keyboard.sh
    chmod: '755'
  f_thinkpad-leds.sh:
    src: bin/thinkpad-leds.sh
    dst: ~/.bin/thinkpad-leds.sh
    chmod: '755'
  f_unclutter.sh:
    src: bin/unclutter.sh
    dst: ~/.bin/unclutter.sh
    chmod: '755'
  f_buffer-move.el:
    src: config/emacs/scripts/buffer-move.el
    dst: ~/.config/emacs/scripts/buffer-move.el
  f_elpaca-setup.el:
    src: config/emacs/scripts/elpaca-setup.el
    dst: ~/.config/emacs/scripts/elpaca-setup.el
  f_mindre-theme.el:
    src: config/emacs/scripts/mindre-theme.el
    dst: ~/.config/emacs/scripts/mindre-theme.el
  f_themes.org:
    src: config/emacs/scripts/themes.org
    dst: ~/.config/emacs/scripts/themes.org
  f_postswitch:
    src: config/autorandr/postswitch
    dst: ~/.config/autorandr/postswitch
    chmod: '755'
  f_lock-screen.sh:
    src: bin/lock-screen.sh
    dst: ~/.bin/lock-screen.sh
    chmod: '755'
  f_profile:
    src: profile
    dst: ~/.profile
  f_ec-editor:
    src: bin/ec-editor
    dst: ~/.bin/ec-editor
    chmod: '755'
  f_ec-visual:
    src: bin/ec-visual
    dst: ~/.bin/ec-visual
    chmod: '755'
  f_alacritty.toml:
    src: config/alacritty/alacritty.toml
    dst: ~/.config/alacritty/alacritty.toml
profiles:
  hyper-city:
    dotfiles:
    - f_editorconfig
    - f_fdignore
    - f_rgignore
    - f_ripgreprc
    - f_ini
    - f_ec.desktop
    - f_config.kdl
    - f_config.sh
    - f_gitconfig
    - f_config.org
    - f_early-init.el
    - f_init.el
    - f_config.fish
    - f_fish_plugins
    - f_ec
    - f_keyboard.sh
    - f_thinkpad-leds.sh
    - f_unclutter.sh
    - f_buffer-move.el
    - f_elpaca-setup.el
    - f_mindre-theme.el
    - f_themes.org
    - f_lock-screen.sh
    - f_profile
    - f_ec-editor
    - f_ec-visual
    - f_alacritty.toml
  ismd-work:
    dotfiles:
    - f_editorconfig
    - f_fdignore
    - f_rgignore
    - f_ripgreprc
    - d_gammastep
    - f_ini
    - d_doom
    - f_mimeapps.list
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_ec.desktop
    - f_vconsole.conf
    - f_xprofile
    - f_tmux.conf
    - f_config.kdl
    - f_config.sh
    - d_config.d
    - f_modules.ini
    - f_gitconfig
    - f_config.org
    - f_early-init.el
    - f_init.el
    - f_config.fish
    - f_fish_plugins
    - f_ec
    - f_gammastep.sh
    - f_keyboard.sh
    - f_thinkpad-leds.sh
    - f_unclutter.sh
    - f_buffer-move.el
    - f_elpaca-setup.el
    - f_mindre-theme.el
    - f_themes.org
    - f_lock-screen.sh
    - f_profile
    - f_ec-editor
    - f_ec-visual
    - f_alacritty.toml
