#!/usr/bin/env bash

set -euo pipefail

gotroot=$(sh -c "sudo -vn" 2>&1 || true)

if [[ "$gotroot" =~ "password" ]]; then
    echo "Sudo access is required to run this script. Authorize sudo and try again."
    exit 1
fi

yay -S --noconfirm --needed \
    7zip \
    adw-gtk-theme \
    aria2 \
    ark \
    avahi \
    bash-language-server \
    bind \
    bitwarden-desktop \
    caido-desktop \
    calf \
    cmake \
    cups-pk-helper \
    direnv \
    discord \
    dms-shell \
    dms-shell-hyprland \
    dnsmasq \
    docker \
    docker-buildx \
    docker-compose \
    docker-credential-secretservice \
    dolphin \
    dosfstools \
    downgrade \
    e2fsprogs \
    easyeffects \
    easytag \
    elephant \
    elephant-calc \
    elephant-desktopapplications \
    elephant-providerlist \
    elephant-symbols \
    elephant-unicode \
    elephant-websearch \
    emacs-wayland \
    evince \
    exfat-utils \
    eza \
    fatresize \
    fd \
    ffmpeg \
    ffmpegthumbnailer \
    ffuf \
    fish-lsp \
    fwupd \
    gimp \
    git \
    github-cli \
    gobuster \
    gopls \
    helm \
    hunspell-en_US \
    hunspell-ru \
    hydra \
    hypridle \
    hyprpolkitagent \
    hyprsunset \
    i2c-tools \
    imagemagick \
    imhex-bin \
    inetutils \
    intel-media-driver \
    k9s \
    kdeconnect \
    kimageformats \
    kubectl \
    libreoffice-still \
    libva-utils \
    libvips \
    libvirt \
    libvterm \
    libtool \
    lsp-plugins-lv2 \
    mc \
    mediainfo \
    neovim \
    nftables \
    nmap \
    noto-fonts-emoji \
    nss-mdns \
    ntfs-3g \
    openbsd-netcat \
    openlens-bin \
    partitionmanager \
    pavucontrol \
    perl-image-exiftool \
    plymouth \
    podman-desktop \
    pyright \
    python-beautifulsoup4 \
    python-pip \
    python-pipx \
    python-pylast \
    python-pylint \
    python-pywal \
    qemu-full \
    qt6-tools \
    qt6ct-kde \
    quickshell-git \
    remmina \
    ripgrep \
    socat \
    sshfs \
    swww \
    tigervnc \
    tlp \
    tlp-pd \
    ttf-firacode-nerd \
    ttf-meslo-nerd \
    ttf-nerd-fonts-symbols \
    ttf-sourcecodepro-nerd \
    ttf-ubuntu-nerd \
    viewnior \
    vpl-gpu-rt \
    vscode-json-languageserver \
    whois \
    xdg-desktop-portal-hyprland \
    xournalpp \
    yaml-language-server \
    zen-browser-bin \
    zoom
