-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Nordzy-cursors")
hl.env("XCURSOR_THEME", "Nordzy-cursors")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("XCURSOR_SIZE", "32")

hl.config({
	cursor = {
		hide_on_key_press = true,
		inactive_timeout = 2,
	},
})
