#+title: Languages
#+author: Vladimir Kosteley
#+description: Programming language support, LSP, and tree-sitter
#+options: toc:2

* Table of Contents :toc:
- [[#eglot][Eglot]]
- [[#flymake][Flymake]]
- [[#jsonrpc][JSONRPC]]
- [[#kirigami][Kirigami]]
- [[#kubernetes][Kubernetes]]
  - [[#kele][kele]]
  - [[#kubed][Kubed]]
  - [[#kubel][kubel]]
  - [[#kubernetes-el][kubernetes-el]]
- [[#language-support][Language Support]]
  - [[#dart][Dart]]
  - [[#fish][Fish]]
  - [[#go][Go]]
  - [[#markdown][Markdown]]
  - [[#python][Python]]
  - [[#qml][QML]]
  - [[#terraform][Terraform]]
- [[#nvm][Nvm]]
- [[#protobuf][Protobuf]]
- [[#tree-sitter][Tree Sitter]]
  - [[#treesit-auto][Treesit Auto]]
  - [[#treesit-fold][Treesit Fold]]

* Eglot
https://github.com/joaotavora/eglot

#+begin_src emacs-lisp
(use-package eglot
  :ensure t
  :hook ((prog-mode . eglot-ensure))
  :config
  (advice-add 'eglot--message :around
              (lambda (orig format &rest args)
                (unless (string-prefix-p "Connected!" format)
                  (apply orig format args)))))
#+end_src

* Flymake
#+begin_src emacs-lisp
(use-package flymake
  :ensure t)
#+end_src

* JSONRPC
#+begin_src emacs-lisp
(use-package jsonrpc
  :ensure t)
#+end_src

* Kirigami
https://github.com/jamescherti/kirigami.el

#+begin_src emacs-lisp
(use-package kirigami
  :ensure t)
#+end_src

* Kubernetes
** kele
https://github.com/jinnovation/kele.el

Actively developed. Modern Emacs-native UI with Embark integration. Confusing keybindings.

#+begin_src emacs-lisp
(use-package kele
  :ensure t
  :defer t
  :config
  (kele-mode 1))
#+end_src

** Kubed
https://github.com/eshelyaron/kubed

Actively developed. Alternative to kele with TRAMP integration.

#+begin_src emacs-lisp
(use-package kubed
  :ensure t
  :defer t)
#+end_src

** kubel
https://github.com/abrochard/kubel

Maintained, accepts PRs. Good for limited RBAC permissions.

#+begin_src emacs-lisp
(use-package kubel
  :ensure t
  :defer t
  :after vterm
  :config (kubel-vterm-setup))
#+end_src

** kubernetes-el
https://github.com/kubernetes-el/kubernetes-el

Maintained (mostly CI updates). Most popular (679 stars) but has performance issues.

#+begin_src emacs-lisp
(use-package kubernetes
  :ensure t
  :defer t)
#+end_src

* Language Support
Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK, C, C++, Fortran, Icon, IDL (CORBA), IDLWAVE, Java, Javascript, M4, Makefiles, Metafont, Modula2, Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby, Simula, SQL, Tcl, Verilog, and VHDL.  Other languages will require you to install additional modes.

** Dart
https://github.com/emacsorphanage/dart-mode
https://emacs-lsp.github.io/lsp-dart/

#+begin_src emacs-lisp
(use-package dart-mode
  :ensure t)
#+end_src

*** Flutter
https://github.com/amake/flutter.el

#+begin_src emacs-lisp
(use-package flutter
  :ensure t
  :after dart-mode
  :bind (:map dart-mode-map
              ("C-M-x" . #'flutter-run-or-hot-reload)))
#+end_src

** Fish
https://github.com/emacsmirror/fish-mode

#+begin_src emacs-lisp
(use-package fish-mode
  :ensure t)
#+end_src

** Go
https://github.com/dominikh/go-mode.el

#+begin_src emacs-lisp
(use-package go-mode
  :ensure t)
#+end_src

** Markdown
*** Grip
https://github.com/seagle0128/grip-mode

#+begin_src emacs-lisp
(use-package grip-mode
  :ensure t
  :bind (:map markdown-mode-command-map
              ("g" . grip-mode)))
#+end_src

** Python
*** Elpy
https://github.com/jorgenschaefer/elpy

#+begin_src emacs-lisp
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
#+end_src

*** Pet
https://github.com/wyuenho/emacs-pet

#+begin_src emacs-lisp
(use-package pet
  :ensure t
  :custom
  (python-indent-guess-indent-offset-verbose nil)
  :config
  (add-hook 'python-base-mode-hook 'pet-mode -10))
#+end_src

** QML
https://github.com/coldnew/qml-mode

#+begin_src emacs-lisp
(use-package qml-mode
  :ensure t)
#+end_src

** Terraform
#+begin_src emacs-lisp
(use-package terraform-mode
  :ensure t
  :custom
  (terraform-indent-level 2)
  (terraform-format-on-save nil))
#+end_src

* Nvm
https://github.com/rejeep/nvm.el

#+begin_src emacs-lisp
(use-package nvm
  :ensure (:host github :repo "rejeep/nvm.el")
  :config
  (nvm-use "24"))
#+end_src

* Protobuf
#+begin_src emacs-lisp
(use-package protobuf-mode
  :ensure t)
#+end_src

* Tree Sitter
Before Emacs 29, tree-sitter was a [[https://emacs-tree-sitter.github.io/][package]] that could be installed. With Emacs 29, tree-sitter is built-in in package =treesit.el=.

** Treesit Auto
#+begin_src emacs-lisp
(use-package treesit-auto
  :ensure t
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
#+end_src

** Treesit Fold
https://github.com/emacs-tree-sitter/treesit-fold

#+begin_src emacs-lisp
(use-package treesit-fold
  :ensure (:host github :repo "emacs-tree-sitter/treesit-fold")
  :custom
  (treesit-fold-line-count-format (concat (truncate-string-ellipsis) " %d lines " (truncate-string-ellipsis)))
  (treesit-fold-line-count-show t)
  :config
  (global-treesit-fold-mode 1)
  ;; Disabled because it is too slow
  ;; (global-treesit-fold-indicators-mode 1)
  )
#+end_src
