#+title: Languages
#+author: Vladimir Kosteley
#+description: Programming language support, LSP, and tree-sitter
#+startup: showeverything

* Table of Contents :toc:
- [[#eglot][Eglot]]
- [[#flymake][Flymake]]
- [[#flyover][Flyover]]
- [[#jsonrpc][JSONRPC]]
- [[#kubernetes][Kubernetes]]
  - [[#kele][kele]]
  - [[#kubed][Kubed]]
  - [[#kubel][kubel]]
  - [[#kubernetes-el][kubernetes-el]]
- [[#language-support][Language Support]]
  - [[#dart][Dart]]
  - [[#fish][Fish]]
  - [[#go][Go]]
  - [[#python][Python]]
  - [[#qml][QML]]
  - [[#terraform][Terraform]]
- [[#nvm][Nvm]]
- [[#protobuf][Protobuf]]
- [[#tree-sitter][Tree Sitter]]
  - [[#treesit-auto][Treesit Auto]]
  - [[#treesit-fold][Treesit Fold]]

* Eglot
https://github.com/joaotavora/eglot

#+begin_src emacs-lisp
(use-package eglot
  :ensure nil
  :hook ((bash-ts-mode
          dart-mode
          fish-mode
          go-mode go-ts-mode
          js-mode js-ts-mode
          json-mode json-ts-mode
          python-mode python-ts-mode
          qml-mode
          sh-mode
          terraform-mode
          tsx-ts-mode
          typescript-mode typescript-ts-mode
          yaml-mode yaml-ts-mode) . eglot-ensure)
  :config
  (add-to-list 'eglot-server-programs '(fish-mode "fish-lsp" "start"))
  (add-to-list 'eglot-server-programs '(qml-mode "qmlls6"))
  (advice-add 'eglot--message :around
              (lambda (orig format &rest args)
                (unless (string-prefix-p "Connected!" format)
                  (apply orig format args)))))
#+end_src

* Flymake
#+begin_src emacs-lisp
(use-package flymake
  :ensure nil)
#+end_src

* Flyover
https://github.com/konrad1977/flyover

#+begin_src emacs-lisp
(use-package flyover
  :ensure t
  :hook ((flymake-mode . flyover-mode))
  :custom
  ;; Checker settings
  (flyover-checkers '(flymake))
  (flyover-levels '(error warning info))

  ;; Appearance
  (flyover-use-theme-colors t)
  (flyover-background-lightness 45)

  ;; Text tinting
  (flyover-text-tint 'lighter)
  (flyover-text-tint-percent 50)

  ;; Icon tinting (foreground and background)
  (flyover-icon-tint 'lighter)
  (flyover-icon-tint-percent 50)
  (flyover-icon-background-tint 'darker)
  (flyover-icon-background-tint-percent 50)

  ;; Icons
  (flyover-info-icon " ")
  (flyover-warning-icon " ")
  (flyover-error-icon " ")

  ;; Border styles: none, pill, arrow, slant, slant-inv, flames, pixels
  (flyover-border-style 'pill)
  (flyover-border-match-icon t)

  ;; Display settings
  (flyover-hide-checker-name t)
  (flyover-show-virtual-line t)
  (flyover-virtual-line-type 'curved-dotted-arrow)
  (flyover-line-position-offset 1)

  ;; Message wrapping
  (flyover-wrap-messages t)
  (flyover-max-line-length 80)

  ;; Performance
  (flyover-debounce-interval 0.2)
  (flyover-cursor-debounce-interval 0.3)

  ;; Display mode (controls cursor-based visibility)
  (flyover-display-mode 'always)

  ;; Completion integration
  (flyover-hide-during-completion t))
#+end_src

* JSONRPC
#+begin_src emacs-lisp
(use-package jsonrpc
  :ensure nil)
#+end_src

* Kubernetes
** kele
https://github.com/jinnovation/kele.el

Actively developed. Modern Emacs-native UI with Embark integration. Confusing keybindings.

#+begin_src emacs-lisp
(use-package kele
  :ensure t
  :defer t
  :config
  (kele-mode 1))
#+end_src

** Kubed
https://github.com/eshelyaron/kubed

Actively developed. Alternative to kele with TRAMP integration.

#+begin_src emacs-lisp
(use-package kubed
  :ensure t
  :defer t)
#+end_src

** kubel
https://github.com/abrochard/kubel

Maintained, accepts PRs. Good for limited RBAC permissions.

#+begin_src emacs-lisp
(use-package kubel
  :ensure t
  :defer t
  :after vterm
  :config (kubel-vterm-setup))
#+end_src

** kubernetes-el
https://github.com/kubernetes-el/kubernetes-el

Maintained (mostly CI updates). Most popular (679 stars) but has performance issues.

#+begin_src emacs-lisp
(use-package kubernetes
  :ensure t
  :defer t)
#+end_src

* Language Support
Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK, C, C++, Fortran, Icon, IDL (CORBA), IDLWAVE, Java, Javascript, M4, Makefiles, Metafont, Modula2, Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby, Simula, SQL, Tcl, Verilog, and VHDL.  Other languages will require you to install additional modes.

** Dart
https://github.com/emacsorphanage/dart-mode
https://emacs-lsp.github.io/lsp-dart/

#+begin_src emacs-lisp
(use-package dart-mode
  :ensure t)
#+end_src

*** Flutter
https://github.com/amake/flutter.el

#+begin_src emacs-lisp
(use-package flutter
  :ensure t
  :after dart-mode
  :bind (:map dart-mode-map
              ("C-M-x" . #'flutter-run-or-hot-reload)))
#+end_src

** Fish
https://github.com/emacsmirror/fish-mode

#+begin_src emacs-lisp
(use-package fish-mode
  :ensure t)
#+end_src

** Go
https://github.com/dominikh/go-mode.el

#+begin_src emacs-lisp
(use-package go-mode
  :ensure t)
#+end_src

** Python
*** Elpy
https://github.com/jorgenschaefer/elpy

#+begin_src emacs-lisp
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
#+end_src

*** Pet
https://github.com/wyuenho/emacs-pet

#+begin_src emacs-lisp
(use-package pet
  :ensure t
  :custom
  (python-indent-guess-indent-offset-verbose nil)
  :config
  (add-hook 'python-base-mode-hook 'pet-mode -10))
#+end_src

** QML
https://github.com/coldnew/qml-mode

#+begin_src emacs-lisp
(use-package qml-mode
  :ensure t)
#+end_src

** Terraform
#+begin_src emacs-lisp
(use-package terraform-mode
  :ensure t
  :custom
  (terraform-indent-level 2)
  (terraform-format-on-save nil))
#+end_src

* Nvm
https://github.com/rejeep/nvm.el

#+begin_src emacs-lisp
(use-package nvm
  :ensure (:host github :repo "rejeep/nvm.el")
  :config
  (nvm-use "24"))
#+end_src

* Protobuf
#+begin_src emacs-lisp
(use-package protobuf-mode
  :ensure t)
#+end_src

* Tree Sitter
Before Emacs 29, tree-sitter was a [[https://emacs-tree-sitter.github.io/][package]] that could be installed. With Emacs 29, tree-sitter is built-in in package =treesit.el=.

** Treesit Auto
#+begin_src emacs-lisp
(use-package treesit-auto
  :ensure t
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
#+end_src

** Treesit Fold
https://github.com/emacs-tree-sitter/treesit-fold

#+begin_src emacs-lisp
(use-package treesit-fold
  :ensure (:host github :repo "emacs-tree-sitter/treesit-fold")
  :custom
  (treesit-fold-line-count-format (concat (truncate-string-ellipsis) " %d lines " (truncate-string-ellipsis)))
  (treesit-fold-line-count-show t)
  :config
  (global-treesit-fold-mode 1)
  ;; Disabled because it is too slow
  ;; (global-treesit-fold-indicators-mode 1)
  )
#+end_src
