#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop comment "early drop of invalid connections"
    ct state {established, related} accept comment "allow tracked connections"
    iif lo accept comment "allow from loopback"
    iifname "docker0" accept comment "allow from docker"
    iifname "virbr*" accept comment "allow from libvirt"
    ip protocol icmp accept comment "allow icmp"
    meta l4proto ipv6-icmp accept comment "allow icmp v6"
    # tcp dport ssh accept comment "allow sshd"

    ip saddr 192.168.0.0/16 udp dport 5353 accept comment "allow mDNS (avahi)"

    ip saddr 192.168.0.0/16 tcp dport 1714-1764 accept comment "allow KDE Connect"
    ip saddr 192.168.0.0/16 udp dport 1714-1764 accept comment "allow KDE Connect"

    ip saddr 192.168.0.0/16 tcp dport { 47984, 47989, 47990, 48010 } accept comment "allow Sunshine"
    ip saddr 192.168.0.0/16 udp dport { 47998-48000, 48002 } accept comment "allow Sunshine"

    tcp dport 1234-1240 accept comment "CTF ports"
    tcp dport 4444 accept comment "CTF port"

    ip saddr 192.168.0.0/16 tcp dport 8080 accept comment "allow firebase authentication emulator from LAN"
    ip saddr 192.168.0.0/16 tcp dport 9099 accept comment "allow firebase firestore emulator from LAN"

    ip saddr 192.168.0.0/16 tcp dport 8888 accept comment "allow tinyproxy from LAN"

    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
  }

  chain forward {
    type filter hook forward priority filter
    policy drop

    ct state {established, related} accept comment "allow tracked connections"
    iifname "br-*" accept comment "allow docker compose bridges outbound"
    oifname "br-*" accept comment "allow docker compose bridges inbound"
    iifname "docker0" accept comment "allow docker outbound"
    oifname "docker0" accept comment "allow docker inbound"
    iifname "virbr*" accept comment "allow libvirt outbound"
    oifname "virbr*" accept comment "allow libvirt inbound"
  }
}

table ip nat {
  chain postrouting {
    type nat hook postrouting priority srcnat

    oifname != "docker0" ip saddr 172.17.0.0/16 masquerade comment "docker NAT"
    oifname != "br-*" ip saddr 172.16.0.0/12 masquerade comment "docker compose NAT"
  }
}
